FROM    centos:6

MAINTAINER Phil Zimmerman <phil.zimmerman@twcable.com>

# enable EPEL and install wget
RUN     rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm && \
yum -y install wget; yum -y clean all
